# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='navigation_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_title', models.CharField(blank=True, max_length=255, null=True)),
                ('nav_url', models.CharField(blank=True, max_length=255, null=True)),
                ('nav_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAN', to='appscan.navigation')),
            ],
        ),
        migrations.CreateModel(
            name='poc_list',
            fields=[
                ('appName', models.CharField(blank=True, max_length=255, null=True)),
                ('appPowerLink', models.CharField(blank=True, max_length=255, null=True)),
                ('appVersion', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('createDate', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField()),
                ('install_requires', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('references', models.CharField(blank=True, max_length=255, null=True)),
                ('samples', models.CharField(blank=True, max_length=255, null=True)),
                ('updateDate', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('vulID', models.IntegerField(primary_key=True, serialize=False)),
                ('vulType', models.CharField(blank=True, max_length=255, null=True)),
                ('cvss', models.CharField(blank=True, max_length=255, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vul_scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('appname', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('pocname', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
