# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appscan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vul_scan',
        ),
    ]
