# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscan', '0003_vul_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vul_scan',
            name='cvss',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
