# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-08 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appscan', '0006_license'),
    ]

    operations = [
        migrations.DeleteModel(
            name='license',
        ),
    ]
