# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscan', '0007_delete_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='vul_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('vulname', models.CharField(blank=True, max_length=255, null=True)),
                ('cvss', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(default='\u672a\u4fee\u590d', max_length=255)),
            ],
        ),
    ]
