# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-28 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider_conf',
            name='type_vul',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
