# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-28 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0003_auto_20180828_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spider',
            old_name='type_vul',
            new_name='vulid',
        ),
    ]
