# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0004_auto_20180828_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomeye_host',
            name='vulid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoomeye_web',
            name='vulid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
